version: '3'

networks:
  oauthserver-openiddict:
    name: oauthserver-openiddict
 
services:

  oauthserver-openiddict:
    container_name: oauthserver-openiddict
    networks:
      - oauthserver-openiddict
    build: 
      context: ./
      dockerfile: Dockerfile
    image: oauthserver-openiddict:latest
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      - ConnectionStrings:DefaultConnection=host=postgres-oauthserver;port=5432;database=openiddict;username=openiddict;password=openiddict;

  postgres:
    container_name: postgres-oauthserver
    networks:
      - oauthserver-openiddict
    hostname: postgres-oauthserver
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=openiddict
      - POSTGRES_PASSWORD=openiddict
      - POSTGRES_DB=openiddict
  
  adminer:
    container_name: adminer
    networks:
      - oauthserver-openiddict
    image: adminer
    ports:
      - '8080:8080'