name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: .NET Build IdentityServer
      id: dotnetbuild-idsvr
      run: |
        cd OAuthServer.IdentityServer/src
        dotnet publish -c Release

    - name: .NET Build OpenIdDict
      id: dotnetbuild-openiddict
      run: |
        cd OAuthServer.OpenIdDict/src
        dotnet publish -c Release

    - name: Docker build & push IdentityServer
      id: dockerpublish-idsvr
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ github.token }}
        context: OAuthServer.IdentityServer/src
        imageName: oauthserver-identityserver 

    - name: Docker build & push OpenIdDict
      id: dockerpublish-openiddict
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ github.token }}
        context: OAuthServer.OpenIdDict/src
        imageName: oauthserver-openiddict 

    - name: Print Image URLs
      run: | 
        echo ${{ steps.dockerpublish-idsvr.outputs.imageURL }}
        echo ${{ steps.dockerpublish-openiddict.outputs.imageURL }}
