name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: .NET Build
      id: dotnetbuild
      run: |
        cd OAuthServer.IdentityServer/src
        dotnet publish -c Release
    - name: Docker Build
      id: dockerbuild
      run: |
        cd OAuthServer.IdentityServer/src
        docker build -t "yetanotherchris/oauthserver-identityserver:latest" .
    - name: Docker
      id: dockerpublish
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ github.token }}
        tag: yetanotherchris/oauthserver-identityserver:latest
    - name: Print Image URL
      run: echo ${{ steps.dockerpublish.outputs.imageURL }}
