version: '3'
services:
  
  oauthserver:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    #volumes:
    #  - '~/oauthserver:/app/Config'

  oauthdebugger:
    build:
      context: https://github.com/yetanotherchris/oauth2-oidc-debugger.git
      dockerfile: Dockerfile

    ports:
      - '3000:3000'
